export interface LanguageConfig {
  code: string;
  nativeName: string;
  englishName: string;
  flag: string;
  voiceLang: string;
  speechLang: string;
}

export const LANGUAGES: LanguageConfig[] = [
  { code: 'ru', nativeName: 'Русский', englishName: 'Russian', flag: '🇷🇺', voiceLang: 'ru-RU', speechLang: 'ru-RU' },
  { code: 'en', nativeName: 'English', englishName: 'English', flag: '🇬🇧', voiceLang: 'en-US', speechLang: 'en-US' },
  { code: 'uz', nativeName: "O'zbek", englishName: 'Uzbek', flag: '🇺🇿', voiceLang: 'uz-UZ', speechLang: 'uz-UZ' },
  { code: 'uk', nativeName: 'Українська', englishName: 'Ukrainian', flag: '🇺🇦', voiceLang: 'uk-UA', speechLang: 'uk-UA' },
  { code: 'kk', nativeName: 'Қазақ', englishName: 'Kazakh', flag: '🇰🇿', voiceLang: 'kk-KZ', speechLang: 'kk-KZ' },
  { code: 'tr', nativeName: 'Türkçe', englishName: 'Turkish', flag: '🇹🇷', voiceLang: 'tr-TR', speechLang: 'tr-TR' },
  { code: 'de', nativeName: 'Deutsch', englishName: 'German', flag: '🇩🇪', voiceLang: 'de-DE', speechLang: 'de-DE' },
  { code: 'fr', nativeName: 'Français', englishName: 'French', flag: '🇫🇷', voiceLang: 'fr-FR', speechLang: 'fr-FR' },
  { code: 'es', nativeName: 'Español', englishName: 'Spanish', flag: '🇪🇸', voiceLang: 'es-ES', speechLang: 'es-ES' },
  { code: 'it', nativeName: 'Italiano', englishName: 'Italian', flag: '🇮🇹', voiceLang: 'it-IT', speechLang: 'it-IT' },
  { code: 'pt', nativeName: 'Português', englishName: 'Portuguese', flag: '🇵🇹', voiceLang: 'pt-PT', speechLang: 'pt-PT' },
  { code: 'pl', nativeName: 'Polski', englishName: 'Polish', flag: '🇵🇱', voiceLang: 'pl-PL', speechLang: 'pl-PL' },
  { code: 'nl', nativeName: 'Nederlands', englishName: 'Dutch', flag: '🇳🇱', voiceLang: 'nl-NL', speechLang: 'nl-NL' },
  { code: 'sv', nativeName: 'Svenska', englishName: 'Swedish', flag: '🇸🇪', voiceLang: 'sv-SE', speechLang: 'sv-SE' },
  { code: 'da', nativeName: 'Dansk', englishName: 'Danish', flag: '🇩🇰', voiceLang: 'da-DK', speechLang: 'da-DK' },
  { code: 'nb', nativeName: 'Norsk', englishName: 'Norwegian', flag: '🇳🇴', voiceLang: 'nb-NO', speechLang: 'nb-NO' },
  { code: 'fi', nativeName: 'Suomi', englishName: 'Finnish', flag: '🇫🇮', voiceLang: 'fi-FI', speechLang: 'fi-FI' },
  { code: 'cs', nativeName: 'Čeština', englishName: 'Czech', flag: '🇨🇿', voiceLang: 'cs-CZ', speechLang: 'cs-CZ' },
  { code: 'sk', nativeName: 'Slovenčina', englishName: 'Slovak', flag: '🇸🇰', voiceLang: 'sk-SK', speechLang: 'sk-SK' },
  { code: 'hu', nativeName: 'Magyar', englishName: 'Hungarian', flag: '🇭🇺', voiceLang: 'hu-HU', speechLang: 'hu-HU' },
  { code: 'ro', nativeName: 'Română', englishName: 'Romanian', flag: '🇷🇴', voiceLang: 'ro-RO', speechLang: 'ro-RO' },
  { code: 'bg', nativeName: 'Български', englishName: 'Bulgarian', flag: '🇧🇬', voiceLang: 'bg-BG', speechLang: 'bg-BG' },
  { code: 'el', nativeName: 'Ελληνικά', englishName: 'Greek', flag: '🇬🇷', voiceLang: 'el-GR', speechLang: 'el-GR' },
  { code: 'sr', nativeName: 'Српски', englishName: 'Serbian', flag: '🇷🇸', voiceLang: 'sr-RS', speechLang: 'sr-RS' },
  { code: 'hr', nativeName: 'Hrvatski', englishName: 'Croatian', flag: '🇭🇷', voiceLang: 'hr-HR', speechLang: 'hr-HR' },
  { code: 'sl', nativeName: 'Slovenščina', englishName: 'Slovenian', flag: '🇸🇮', voiceLang: 'sl-SI', speechLang: 'sl-SI' },
  { code: 'lt', nativeName: 'Lietuvių', englishName: 'Lithuanian', flag: '🇱🇹', voiceLang: 'lt-LT', speechLang: 'lt-LT' },
  { code: 'lv', nativeName: 'Latviešu', englishName: 'Latvian', flag: '🇱🇻', voiceLang: 'lv-LV', speechLang: 'lv-LV' },
  { code: 'et', nativeName: 'Eesti', englishName: 'Estonian', flag: '🇪🇪', voiceLang: 'et-EE', speechLang: 'et-EE' },
  { code: 'sq', nativeName: 'Shqip', englishName: 'Albanian', flag: '🇦🇱', voiceLang: 'sq-AL', speechLang: 'sq-AL' },
  { code: 'mk', nativeName: 'Македонски', englishName: 'Macedonian', flag: '🇲🇰', voiceLang: 'mk-MK', speechLang: 'mk-MK' },
  { code: 'bs', nativeName: 'Bosanski', englishName: 'Bosnian', flag: '🇧🇦', voiceLang: 'bs-BA', speechLang: 'bs-BA' },
  { code: 'ar', nativeName: 'العربية', englishName: 'Arabic', flag: '🇸🇦', voiceLang: 'ar-SA', speechLang: 'ar-SA' },
  { code: 'he', nativeName: 'עברית', englishName: 'Hebrew', flag: '🇮🇱', voiceLang: 'he-IL', speechLang: 'he-IL' },
  { code: 'fa', nativeName: 'فارسی', englishName: 'Persian', flag: '🇮🇷', voiceLang: 'fa-IR', speechLang: 'fa-IR' },
  { code: 'ur', nativeName: 'اردو', englishName: 'Urdu', flag: '🇵🇰', voiceLang: 'ur-PK', speechLang: 'ur-PK' },
  { code: 'hi', nativeName: 'हिन्दी', englishName: 'Hindi', flag: '🇮🇳', voiceLang: 'hi-IN', speechLang: 'hi-IN' },
  { code: 'bn', nativeName: 'বাংলা', englishName: 'Bengali', flag: '🇧🇩', voiceLang: 'bn-BD', speechLang: 'bn-BD' },
  { code: 'ta', nativeName: 'தமிழ்', englishName: 'Tamil', flag: '🇮🇳', voiceLang: 'ta-IN', speechLang: 'ta-IN' },
  { code: 'te', nativeName: 'తెలుగు', englishName: 'Telugu', flag: '🇮🇳', voiceLang: 'te-IN', speechLang: 'te-IN' },
  { code: 'mr', nativeName: 'मराठी', englishName: 'Marathi', flag: '🇮🇳', voiceLang: 'mr-IN', speechLang: 'mr-IN' },
  { code: 'gu', nativeName: 'ગુજરાતી', englishName: 'Gujarati', flag: '🇮🇳', voiceLang: 'gu-IN', speechLang: 'gu-IN' },
  { code: 'kn', nativeName: 'ಕನ್ನಡ', englishName: 'Kannada', flag: '🇮🇳', voiceLang: 'kn-IN', speechLang: 'kn-IN' },
  { code: 'ml', nativeName: 'മലയാളം', englishName: 'Malayalam', flag: '🇮🇳', voiceLang: 'ml-IN', speechLang: 'ml-IN' },
  { code: 'pa', nativeName: 'ਪੰਜਾਬੀ', englishName: 'Punjabi', flag: '🇮🇳', voiceLang: 'pa-IN', speechLang: 'pa-IN' },
  { code: 'ne', nativeName: 'नेपाली', englishName: 'Nepali', flag: '🇳🇵', voiceLang: 'ne-NP', speechLang: 'ne-NP' },
  { code: 'si', nativeName: 'සිංහල', englishName: 'Sinhala', flag: '🇱🇰', voiceLang: 'si-LK', speechLang: 'si-LK' },
  { code: 'km', nativeName: 'ភាសាខ្មែរ', englishName: 'Khmer', flag: '🇰🇭', voiceLang: 'km-KH', speechLang: 'km-KH' },
  { code: 'my', nativeName: 'မြန်မာဘာသာ', englishName: 'Burmese', flag: '🇲🇲', voiceLang: 'my-MM', speechLang: 'my-MM' },
  { code: 'th', nativeName: 'ไทย', englishName: 'Thai', flag: '🇹🇭', voiceLang: 'th-TH', speechLang: 'th-TH' },
  { code: 'lo', nativeName: 'ລາວ', englishName: 'Lao', flag: '🇱🇦', voiceLang: 'lo-LA', speechLang: 'lo-LA' },
  { code: 'vi', nativeName: 'Tiếng Việt', englishName: 'Vietnamese', flag: '🇻🇳', voiceLang: 'vi-VN', speechLang: 'vi-VN' },
  { code: 'id', nativeName: 'Bahasa Indonesia', englishName: 'Indonesian', flag: '🇮🇩', voiceLang: 'id-ID', speechLang: 'id-ID' },
  { code: 'ms', nativeName: 'Bahasa Melayu', englishName: 'Malay', flag: '🇲🇾', voiceLang: 'ms-MY', speechLang: 'ms-MY' },
  { code: 'tl', nativeName: 'Filipino', englishName: 'Filipino', flag: '🇵🇭', voiceLang: 'fil-PH', speechLang: 'fil-PH' },
  { code: 'mn', nativeName: 'Монгол', englishName: 'Mongolian', flag: '🇲🇳', voiceLang: 'mn-MN', speechLang: 'mn-MN' },
  { code: 'zh', nativeName: '中文', englishName: 'Chinese (Simplified)', flag: '🇨🇳', voiceLang: 'zh-CN', speechLang: 'zh-CN' },
  { code: 'zh-tw', nativeName: '繁體中文', englishName: 'Chinese (Traditional)', flag: '🇹🇼', voiceLang: 'zh-TW', speechLang: 'zh-TW' },
  { code: 'ja', nativeName: '日本語', englishName: 'Japanese', flag: '🇯🇵', voiceLang: 'ja-JP', speechLang: 'ja-JP' },
  { code: 'ko', nativeName: '한국어', englishName: 'Korean', flag: '🇰🇷', voiceLang: 'ko-KR', speechLang: 'ko-KR' },
  { code: 'ca', nativeName: 'Català', englishName: 'Catalan', flag: '🇪🇸', voiceLang: 'ca-ES', speechLang: 'ca-ES' },
  { code: 'eu', nativeName: 'Euskara', englishName: 'Basque', flag: '🇪🇸', voiceLang: 'eu-ES', speechLang: 'eu-ES' },
  { code: 'gl', nativeName: 'Galego', englishName: 'Galician', flag: '🇪🇸', voiceLang: 'gl-ES', speechLang: 'gl-ES' },
  { code: 'cy', nativeName: 'Cymraeg', englishName: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', voiceLang: 'cy-GB', speechLang: 'cy-GB' },
  { code: 'ga', nativeName: 'Gaeilge', englishName: 'Irish', flag: '🇮🇪', voiceLang: 'ga-IE', speechLang: 'ga-IE' },
  { code: 'gd', nativeName: 'Gàidhlig', englishName: 'Scottish Gaelic', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', voiceLang: 'gd-GB', speechLang: 'gd-GB' },
  { code: 'mt', nativeName: 'Malti', englishName: 'Maltese', flag: '🇲🇹', voiceLang: 'mt-MT', speechLang: 'mt-MT' },
  { code: 'is', nativeName: 'Íslenska', englishName: 'Icelandic', flag: '🇮🇸', voiceLang: 'is-IS', speechLang: 'is-IS' },
  { code: 'lb', nativeName: 'Lëtzebuergesch', englishName: 'Luxembourgish', flag: '🇱🇺', voiceLang: 'lb-LU', speechLang: 'lb-LU' },
  { code: 'af', nativeName: 'Afrikaans', englishName: 'Afrikaans', flag: '🇿🇦', voiceLang: 'af-ZA', speechLang: 'af-ZA' },
  { code: 'sw', nativeName: 'Kiswahili', englishName: 'Swahili', flag: '🇹🇿', voiceLang: 'sw-TZ', speechLang: 'sw-TZ' },
  { code: 'zu', nativeName: 'isiZulu', englishName: 'Zulu', flag: '🇿🇦', voiceLang: 'zu-ZA', speechLang: 'zu-ZA' },
  { code: 'am', nativeName: 'አማርኛ', englishName: 'Amharic', flag: '🇪🇹', voiceLang: 'am-ET', speechLang: 'am-ET' },
  { code: 'ha', nativeName: 'Hausa', englishName: 'Hausa', flag: '🇳🇬', voiceLang: 'ha-NG', speechLang: 'ha-NG' },
  { code: 'ig', nativeName: 'Igbo', englishName: 'Igbo', flag: '🇳🇬', voiceLang: 'ig-NG', speechLang: 'ig-NG' },
  { code: 'yo', nativeName: 'Yorùbá', englishName: 'Yoruba', flag: '🇳🇬', voiceLang: 'yo-NG', speechLang: 'yo-NG' },
  { code: 'ka', nativeName: 'ქართული', englishName: 'Georgian', flag: '🇬🇪', voiceLang: 'ka-GE', speechLang: 'ka-GE' },
  { code: 'hy', nativeName: 'Հայերեն', englishName: 'Armenian', flag: '🇦🇲', voiceLang: 'hy-AM', speechLang: 'hy-AM' },
  { code: 'az', nativeName: 'Azərbaycan', englishName: 'Azerbaijani', flag: '🇦🇿', voiceLang: 'az-AZ', speechLang: 'az-AZ' },
  { code: 'tk', nativeName: 'Türkmen', englishName: 'Turkmen', flag: '🇹🇲', voiceLang: 'tk-TM', speechLang: 'tk-TM' },
  { code: 'ky', nativeName: 'Кыргызча', englishName: 'Kyrgyz', flag: '🇰🇬', voiceLang: 'ky-KG', speechLang: 'ky-KG' },
  { code: 'tg', nativeName: 'Тоҷикӣ', englishName: 'Tajik', flag: '🇹🇯', voiceLang: 'tg-TJ', speechLang: 'tg-TJ' },
  { code: 'ps', nativeName: 'پښتو', englishName: 'Pashto', flag: '🇦🇫', voiceLang: 'ps-AF', speechLang: 'ps-AF' },
  { code: 'sd', nativeName: 'سنڌي', englishName: 'Sindhi', flag: '🇵🇰', voiceLang: 'sd-PK', speechLang: 'sd-PK' },
  { code: 'ku', nativeName: 'Kurdî', englishName: 'Kurdish', flag: '🇹🇷', voiceLang: 'ku-TR', speechLang: 'ku-TR' },
  { code: 'be', nativeName: 'Беларуская', englishName: 'Belarusian', flag: '🇧🇾', voiceLang: 'be-BY', speechLang: 'be-BY' },
  { code: 'mo', nativeName: 'Moldovenească', englishName: 'Moldovan', flag: '🇲🇩', voiceLang: 'ro-MD', speechLang: 'ro-MD' },
  { code: 'jv', nativeName: 'Basa Jawa', englishName: 'Javanese', flag: '🇮🇩', voiceLang: 'jv-ID', speechLang: 'jv-ID' },
  { code: 'su', nativeName: 'Basa Sunda', englishName: 'Sundanese', flag: '🇮🇩', voiceLang: 'su-ID', speechLang: 'su-ID' },
  { code: 'ceb', nativeName: 'Cebuano', englishName: 'Cebuano', flag: '🇵🇭', voiceLang: 'ceb-PH', speechLang: 'ceb-PH' },
  { code: 'mg', nativeName: 'Malagasy', englishName: 'Malagasy', flag: '🇲🇬', voiceLang: 'mg-MG', speechLang: 'mg-MG' },
  { code: 'ny', nativeName: 'Chichewa', englishName: 'Chichewa', flag: '🇲🇼', voiceLang: 'ny-MW', speechLang: 'ny-MW' },
  { code: 'so', nativeName: 'Soomaali', englishName: 'Somali', flag: '🇸🇴', voiceLang: 'so-SO', speechLang: 'so-SO' },
  { code: 'st', nativeName: 'Sesotho', englishName: 'Sesotho', flag: '🇱🇸', voiceLang: 'st-LS', speechLang: 'st-LS' },
  { code: 'tn', nativeName: 'Setswana', englishName: 'Tswana', flag: '🇧🇼', voiceLang: 'tn-BW', speechLang: 'tn-BW' },
  { code: 'xh', nativeName: 'isiXhosa', englishName: 'Xhosa', flag: '🇿🇦', voiceLang: 'xh-ZA', speechLang: 'xh-ZA' },
  { code: 'sn', nativeName: 'chiShona', englishName: 'Shona', flag: '🇿🇼', voiceLang: 'sn-ZW', speechLang: 'sn-ZW' },
];

export function getLanguageConfig(code: string): LanguageConfig {
  return LANGUAGES.find((l) => l.code === code) || LANGUAGES[1];
}
